all(), any()

In [3]:
any([1,2,3,0,5])

True

In [4]:
all([1,2,3,0,5])

False

In [ ]:
# conditional statements
# tossing a coil
# rolling a dice
# i want to perform some operation if some condition is met
# if elif else

In [8]:
if 10 > 20:
    print('yessss')
elif 20 < 30:
    print('May be')
else:
    print('Noooo')

May be


In [9]:
if 10 > 20:
    print('yessss')
elif 20 < 10:
    print('May be')
else:
    print('Noooo')

Noooo


In [14]:
x=None or 0
if x:
    print('Hello')
else:
    print('Bye')

Bye


In [ ]:
if y:
    print('dsjvhbdshv')

In [15]:
'''
if x is not None and len(x) > 0:   if x:

'''

'\nif x is not None and len(x) > 0:   if x:\n\n'

In [16]:
# unpacking

In [17]:
x=10
y=20

In [ ]:
z=x
x=y
y=z

In [ ]:
x=10
y=2
z=5
t=11
i=13

In [18]:
x=10
y=20
x,y=y,x

In [19]:
print(x,y)

20 10


In [20]:
d={
    'x':10,
    'y':20,
    'z':30
}

In [28]:
for i,j in d.items():
    print(i,j)

x 10
y 20
z 30


In [24]:
e1,e2,e3=d.items()

In [25]:
print(e1,e2,e3)

('x', 10) ('y', 20) ('z', 30)


In [26]:
k1,v1=e1
k2,v2=e2
k3,v3=e3

In [27]:
print(k1,v1)

x 10


In [34]:
l1=list(range(1,6))

In [35]:
l2=['a','b','c','d','e']

In [36]:
l3=[*l1,*l2]

In [37]:
l3

[1, 2, 3, 4, 5, 'a', 'b', 'c', 'd', 'e']

In [44]:
a,*b,c=1,2,3,5,6,7 
# user-defined functions ()
# Cannot have multiple starred expressions in assignment

In [42]:
print(a,b,c)

1 [2, 3, 5, 6] 7


In [45]:
d1={'x':1,'y':2}
d2={'y':3,'z':4}   # Thumb rule - Last update always wins
d3={'t':5,'x':7}

In [47]:
d4=dict()

In [50]:
d4={**d3,**d2,**d1}

In [51]:
d4

{'t': 5, 'x': 1, 'y': 2, 'z': 4}

In [61]:
def my_func(*a,**b):   # postional arguments,key-word argument
    print(a,b)

In [62]:
my_func(1,2,3,x=100)   # key-word argument

(1, 2, 3) {'x': 100}


In [ ]:
my_func(1,2,3,x=100)   # key-word argument

In [71]:
def ny_func(*a,**b):
    print(a,b)

In [64]:
my_func()

() {}


In [65]:
my_seq=['x','y','z']
my_info={
    'id':1,
    'name':"Rahul",
    'Working':True
}

In [66]:
my_func(my_seq)

(['x', 'y', 'z'],) {}


In [67]:
my_func(*my_seq)

('x', 'y', 'z') {}


In [68]:
my_func(my_info)

({'id': 1, 'name': 'Rahul', 'Working': True},) {}


In [69]:
my_func(**my_info)

() {'id': 1, 'name': 'Rahul', 'Working': True}


In [70]:
my_func(*my_seq,**my_info)

('x', 'y', 'z') {'id': 1, 'name': 'Rahul', 'Working': True}


In [73]:
def my_func(a,*b,**c): # *a is the mandatory postional arg, 
    print(a,b,c)       # *b: optional postional arg
                         # **c: optional keyword arg

In [76]:
my_func(1,2,3,name='Abdul')

1 (2, 3) {'name': 'Abdul'}


In [79]:
def my_func(a,b,c):
    print(a,b,c)

In [80]:
my_func(a=10,20,30) # we need to continue pass keyword once started

SyntaxError: positional argument follows keyword argument (684757698.py, line 1)

In [83]:
my_func(10,b=20,c=30)

10 20 30


In [85]:
def my_func(a,b,*,c):
    print(a,b,c)

In [87]:
my_func(1,2,c=3)

1 2 3


In [90]:
def my_func(*,c):
    print(c)

In [92]:
my_func(1,2,3)

TypeError: my_func() takes 0 positional arguments but 3 were given

In [96]:
my_func(c=1)

1


In [97]:
def my_func(*,**c):
    print(c)

SyntaxError: named arguments must follow bare * (984202112.py, line 1)

In [104]:
def my_func(a,b=0,c=1):   # default posiotnal arg
    print(a,b,c)

In [106]:
my_func(100)

100 0 1


In [107]:
## once we started defaulting some value of parameters in a function
### the next arguments becomes KEY-WORD ONLY ARGUMENT

In [108]:
def my_func(a,b,*,c,d=5):
    print(a,b,c,d)

In [129]:
def my_func(a,b=0,c=1):   # default posiotnal arg
    print(a,b,c)

In [130]:
my_func(1,2,3)

1 2 3


In [116]:
from datetime import datetime

In [117]:
datetime.utcnow()

C:\Users\tause\AppData\Local\Temp\ipykernel_7288\3983769260.py:1: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  datetime.utcnow()


datetime.datetime(2025, 12, 23, 9, 18, 54, 427602)

In [119]:
Global_timings=datetime.utcnow()

C:\Users\tause\AppData\Local\Temp\ipykernel_7288\2498432501.py:1: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  Global_timings=datetime.utcnow()


In [127]:
def my_time(messsage=a,Timings=datetime.utcnow()):
    print(f"{Timings}:message")

C:\Users\tause\AppData\Local\Temp\ipykernel_7288\313657992.py:1: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  def my_time(messsage=a,Timings=datetime.utcnow()):


In [125]:
datetime.utcnow()

C:\Users\tause\AppData\Local\Temp\ipykernel_7288\3983769260.py:1: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  datetime.utcnow()


datetime.datetime(2025, 12, 23, 9, 22, 30, 630866)

In [128]:
print(datetime.utcnow())
my_time("helllllo greetings........")

2025-12-23 09:23:38.219030
2025-12-23 09:23:24.883248:message


C:\Users\tause\AppData\Local\Temp\ipykernel_7288\2174499616.py:1: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  print(datetime.utcnow())


In [142]:
def my_func(fn,*n):
    return fn(n)

In [143]:
my_func(sum,1,2,3)

6

In [134]:
from math import ad

ImportError: cannot import name 'sum' from 'math' (unknown location)

In [137]:
import cmath

In [138]:
dir(cmath)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atanh',
 'cos',
 'cosh',
 'e',
 'exp',
 'inf',
 'infj',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'log',
 'log10',
 'nan',
 'nanj',
 'phase',
 'pi',
 'polar',
 'rect',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau']

In [139]:
sum([1,2,3])

6

In [146]:
def my_func_1(fn,*n):
    return fn(n)  # sum((1,2,3))

In [147]:
def my_func_2(fn,n):
    return fn(n)

In [148]:
my_func_1(sum,1,2,3)

6

In [151]:
sum((1,2,3))  # integers, are not iterable

6

In [152]:
# Decorators... closures....

In [153]:
def my_add(a,b):
    return a+b
def my_mul(a,b):
    return a*b
def my_div(a,b):
    return a/b
def my_sub(a,b):
    return a-b

In [159]:
def my_add(a,b):
    print('hello world')
    '''This is for the purpose of addition '''
    return a+b

In [160]:
my_add.__doc__

In [161]:
def my_add(a,b):
    '''This is for the purpose of addition '''
    print('hello world')
    return a+b

In [162]:
my_add.__doc__

'This is for the purpose of addition '

In [165]:
#Libraries:numpy
import numpy as np

In [168]:
my_list=[1,2,3,4,5]
type(my_list)

list

In [172]:
my_arr=np.array(my_list)

In [169]:
type(np.array(my_list))

numpy.ndarray

In [173]:
print(my_arr)

[1 2 3 4 5]


In [174]:
my_arr * 3

array([ 3,  6,  9, 12, 15])

In [175]:
np.array([1,2,3]) * 3    # BROADCASTING

array([3, 6, 9])

In [176]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [184]:
x=np.array([[1,2,3],
        [4,5,6]])

In [185]:
y=np.array([10,20,30])

In [186]:
x+y

array([[11, 22, 33],
       [14, 25, 36]])

array([30, 40, 50])

In [225]:
x=np.array([[1],
            [2]])

In [200]:
y=np.array([10])

In [201]:
x+y

array([[11],
       [12]])

In [215]:
np.ones(12).reshape(-1,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [216]:
np.zeros(12).reshape(-1,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [220]:
np.diag((3,4))

array([[3, 0],
       [0, 4]])

In [224]:
np.diagonal(np.diag((3,4)))

array([3, 4])

In [226]:
x=np.array([[1],
            [2]])

In [227]:
x.shape

(2, 1)

In [228]:
x=np.array([1,2,3]) # vector
x.shape

(3,)

In [229]:
y=np.array([10])

In [230]:
y.shape

(1,)

In [232]:
np.dot([1,2,3],[10,10,10])

np.int64(60)

In [233]:
'''
a=xi + yj + zk
b=xi + yj + zk
'''

'\na=xi + yj + zk\nb=xi + yj + zk\n'

In [ ]:
np.linalg.inv()

In [235]:
np.linalg.inv()

TypeError: inv() missing 1 required positional argument: 'a'

In [237]:
matrix=np.array([[2,4],  # singular matrix || = 0
         [4,8]])

In [248]:
try:
    np.linalg.inv(matrix)
except np.linalg.LinAlgError as err:
    print(err,"...oops! silly it has det of 0")

Singular matrix ...oops! silly it has det of 0


In [247]:
np.linalg.inv(matrix)

LinAlgError: Singular matrix

In [249]:
np.linalg.det(matrix)

np.float64(0.0)

In [250]:
np.linalg.pinv(matrix)

array([[0.02, 0.04],
       [0.04, 0.08]])

In [251]:
np.where([10,20,30],10>30,True)

array([False, False, False])

In [255]:
my_condition=np.array(range(1,11)) > 5

In [256]:
my_data=np.array(range(1,11))

In [257]:
my_data[my_condition]

array([ 6,  7,  8,  9, 10])

In [258]:
# failure of Broadcasting
## if values from right to left does't match or either them is 1

In [279]:
x=np.ones((3,4))
y=np.ones((1,4))

In [280]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [281]:
y

array([[1., 1., 1., 1.]])

In [282]:
x+y

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [266]:
x=np.ones((3,4))
y=np.ones((2,1))

In [267]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [268]:
y

array([[1.],
       [1.]])

In [269]:
x+y

ValueError: operands could not be broadcast together with shapes (3,4) (2,1) 

In [270]:
x=np.ones((1,4))
y=np.ones((2,4))

In [271]:
x

array([[1., 1., 1., 1.]])

In [272]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [273]:
x+y

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [274]:
x=np.ones((1,4))
y=np.ones((2,3))

In [275]:
x

array([[1., 1., 1., 1.]])

In [277]:
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [278]:
x+y

ValueError: operands could not be broadcast together with shapes (1,4) (2,3) 

In [283]:
#Mismatched dimensions
import numpy as np

a = np.array([1, 2, 3])      # shape (3,)
b = np.array([4, 5])         # shape (2,)

a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [284]:
import numpy as np

a = np.array([1, 2, 3])      # shape (3,)
b = np.array([1,])         # shape (2,)

a + b

array([2, 3, 4])

In [285]:
A = np.ones((2, 3))    # shape (2,3)
B = np.ones((2, 2))    # shape (2,2)

In [288]:
A + B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [287]:
B

array([[1., 1.],
       [1., 1.]])

In [291]:
A = np.ones((3, 4))
b = np.array([10, 20, 30, 40])  # shape (4,)

A + b

array([[11., 21., 31., 41.],
       [11., 21., 31., 41.],
       [11., 21., 31., 41.]])

In [290]:
b

array([10, 20, 30, 40])